-- Full items and technologies list (and a lot of other things)
-- https://wiki.factorio.com/Data.raw

STARTING_TECHNOLOGIES = {
    "electronics",
    "steam-power",
    "automation-science-pack",
    "electric-mining-drill",
    "fast-inserter",
    "logistics",
    "gun-turret",
    "lamp",
    "automation",
    "repair-pack",
    "military",
    "radar",
    "stone-wall",
    "logistic-science-pack",
    "steel-processing",
    "heavy-armor",
    "steel-axe",
    "advanced-material-processing",
    "automation-2",
    "electric-energy-distribution-1",
    "solar-energy",
    "toolbelt",
    "engine",
    "railway",
    "automobilism"
}

STARTING_ITEMS = {
    { "iron-plate",              300 },
    { "copper-plate",            200 },
    { "electronic-circuit",      400 },
    { "advanced-circuit",        200 },
    { "iron-gear-wheel",         200 },
    { "burner-inserter",         50 },
    { "inserter",                50 },
    { "fast-inserter",           50 },
    { "long-handed-inserter",    50 },
    { "transport-belt",          400 },
    { "underground-belt",        50 },
    { "splitter",                50 },
    { "small-electric-pole",     50 },
    { "medium-electric-pole",    50 },
    { "big-electric-pole",       50 },
    { "electric-mining-drill",   50 },
    { "burner-mining-drill",     49 },
    { "stone-furnace",           49 },
    { "steel-furnace",           50 },
    { "assembling-machine-1",    50 },
    { "pipe",                    100 },
    { "pipe-to-ground",          50 },
    { "steel-chest",             50 },
    { "boiler",                  20 },
    { "steam-engine",            20 },
    { "offshore-pump",           20 },
    { "lab",                     10 },
    { "train-stop",              10 },
    { "rail",                    500 },
    { "locomotive",              5 },
    { "cargo-wagon",             10 },
    { "rail-signal",             50 },
    { "rail-chain-signal",       50 },
    { "solar-panel",             50 },
    { "small-lamp",              50 },
    { "repair-pack",             20 },
    { "car",                     1 },
    { "modular-armor",           1 },
    { "solar-panel-equipment",   5 },
    { "battery-mk3-equipment",   2 },
    { "exoskeleton-equipment",   2 },
    { "night-vision-equipment",  1 },
    { "belt-immunity-equipment", 1 },
}
